!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 36, y: 0, z: 20}
      rotations: [90]
    - !Item
      name: Pillar-Button #using alias for compatibility with v3.1.3
      positions:
      - !Vector3 {x: 38.5, y: 0, z: 18.8}
      rotations: [0]
      moveDurations: [0.1]
      resetDurations: [1.0]
      rewardNames: ["GoodGoal", "BadGoal", "GoodGoalMulti"]
      rewardWeights: [1, 0, 0]
      spawnProbability: 1.0
      rewardSpawnPos: !Vector3 {x: 39, y: 3, z: 22}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 39, y: 0, z: 18.2}
      - !Vector3 {x: 39, y: 0, z: 19.8}
      - !Vector3 {x: 39.8, y: 0, z: 19}
      sizes:
      - !Vector3 {x: 0.4, y: 2, z: 1}
      - !Vector3 {x: 0.4, y: 2, z: 1}
      - !Vector3 {x: 2, y: 2, z: 0.4}
      rotations: [90,90,90]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
  1: !Arena
    pass_mark: 0
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: 30, y: 0, z: 20}
      rotations: [90]
    - !Item
      name: Pillar-Button #using alias for compatibility with v3.1.3
      positions:
      - !Vector3 {x: 38.5, y: 0, z: 18.8}
      rotations: [0]
      moveDurations: [0.1]
      resetDurations: [1.0]
      rewardNames: ["GoodGoal", "BadGoal", "GoodGoalMulti"]
      rewardWeights: [1, 0, 0]
      spawnProbability: 1.0
      rewardSpawnPos: !Vector3 {x: 39, y: 3, z: 22}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 39, y: 0, z: 18.2}
      - !Vector3 {x: 39, y: 0, z: 19.8}
      - !Vector3 {x: 39.8, y: 0, z: 19}
      sizes:
      - !Vector3 {x: 0.4, y: 2, z: 1}
      - !Vector3 {x: 0.4, y: 2, z: 1}
      - !Vector3 {x: 2, y: 2, z: 0.4}
      rotations: [90,90,90]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}