!ArenaConfig
arenas:
  0: !Arena
    pass_mark: 0
    t: 500
    items:
    - !Item
      name: Agent
      positions:
      - !Vector3 {x: -1, y: 0, z: -1}
      rotations: [-1]
    - !Item
      name: SpawnerButton
      positions:
      - !Vector3 {x: 19.2, y: 0, z: 38.5}
      rotations: [90]
      moveDurations: [0.1]
      resetDurations: [1.0]
      rewardNames: ["GoodGoal", "BadGoal", "GoodGoalMulti"]
      rewardWeights: [1, 0, 0]
      spawnProbability: 1.0
      rewardSpawnPos: !Vector3 {x: 22, y: 3, z: 39}
    - !Item
      name: Wall
      positions:
      - !Vector3 {x: 18.2, y: 0, z: 39}
      - !Vector3 {x: 19.8, y: 0, z: 39}
      - !Vector3 {x: 19, y: 0, z: 39.8}
      sizes:
      - !Vector3 {x: 0.4, y: 2, z: 1}
      - !Vector3 {x: 0.4, y: 2, z: 1}
      - !Vector3 {x: 2, y: 2, z: 0.4}
      rotations: [0,0,0]
      colors:
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}
      - !RGB {r: 153, g: 153, b: 153}