wandb_version: 1

policy_type:
  desc: null
  value: CnnLstmPolicy
total_timesteps:
  desc: null
  value: 100000
env_name:
  desc: null
  value: animalai3
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.17.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718018808
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 16
      - 23
      - 35
      4: 3.9.18
      5: 0.17.0
      8:
      - 4
      - 5
      13: darwin-arm64
